import sqlite3
import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from rich.console import Console

console = Console()


def generate_pdf_report():

    case_id = input("\nEnter Case ID : ")

    conn = sqlite3.connect(
        "database/cases.db"
    )

    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM cases WHERE case_id=?",
        (case_id,)
    )

    row = cursor.fetchone()

    conn.close()

    if not row:

        console.print(
            "\n[bold red]Case Not Found[/bold red]"
        )

        input("\nPress Enter...")
        return

    os.makedirs(
        "reports",
        exist_ok=True
    )

    pdf_file = f"reports/{case_id}.pdf"

    doc = SimpleDocTemplate(pdf_file)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "SAFEBYTE — CRYPTOTRACE AI",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "CryptoTrace AI Investigation Report",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            f"<b>Case ID:</b> {row[1]}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Wallet Address:</b> {row[2]}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Wallet Type:</b> {row[3]}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Risk Score:</b> {row[4]}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Status:</b> {row[5]}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Notes:</b> {row[6]}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated By CryptoTrace AI",
            styles["Italic"]
        )
    )

    doc.build(content)

    console.print(
        f"\n[bold green]PDF Generated Successfully[/bold green]"
    )

    console.print(
        f"[bold cyan]{pdf_file}[/bold cyan]"
    )

    input("\nPress Enter...")
